This module provides inventory and remediation for the Red Hat Enterprise Linux 7 Security Technical Implementation Guide.

* Configuration
** Classes
- =Red_Hat_Enterprise_Linux_7_STIG:supported_os= controls which hosts the policy and compliance report target. =(centos_7|redhat_7)= by default.
- =Red_Hat_Enterprise_Linux_7_STIG:DEBUG= causes the policy to emit more details.
- =Red_Hat_Enterprise_Linux_7_STIG:<canonified finding id>_remediation_enabled= enables automatic remediation (if available) for the specific finding. Defined if =V-1234= found in  =Red_Hat_Enterprise_Linux_7_STIG:config.remediation_enabled=
- =Red_Hat_Enterprise_Linux_7_STIG:supported_os.Red_Hat_Enterprise_Linux_7_STIG:chaos_enabled= - Causes policy that will modify the system to trigger findings (to be removed).
** Variables
- =Red_Hat_Enterprise_Linux_7_STIG:config.remediation_enabled= - A list of finding IDs for which remediation is enabled if available.

* Inventory
- =Red Hat Enterprise Linux 7 STIG V1 findings= - IDs of findings detected.
- =Red Hat Enterprise Linux 7 STIG V1 findings detail <finding id>= - Useful details about findings. Not available for all findings.
