SSH allows several different ways to authenticate: passwords, keys are two of them. The number of attempts can be reduced to prevent brute force attacks where different passwords are guessed and tried.
By default 6 attempts are allowed per session. Reducing this to 4 is recommended and an excellent idea in environments where the value may have been configured higher.
When half of the attempts are used up failures will be logged on the server making it more likely that an administrator will notice brute force login attempts.

* How it works

This module ensures that =MaxAuthTries= is set to =4= in =/etc/ssh/sshd_config= leveraging =lib_sshd_config:global_key_values= from the [[https://build.cfengine.com/modules/inventory-local-users][lib-sshd-config]] module.

* Variables

The following variables are available for customization. If they are not defined via [[https://docs.cfengine.com/docs/3.18/reference-language-concepts-augments.html][Augments]], they will select default values.

*Note:* In order to target these variables from Augments CFEngine 3.18.0 or higher where [[https://docs.cfengine.com/docs/3.18/reference-language-concepts-augments.html#variables][the =variables= key]] is available is needed.

- =default:ssh_max_auth_tries.sshd_config[MaxAuthTries]= :: Specifies the maximum number of authentication attempts permitted per connection. (default 4)

* Related modules
- [[https://build.cfengine.com/modules/inventory-local-users][lib-sshd-config]]
